<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Graphic.Core\Graphic.Core.csproj" />
      <ProjectReference Include="..\Graphic.DataAccess\Graphic.DataAccess.csproj" />
    </ItemGroup>

</Project>
